before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/guildops
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
  groups:
    - title: New features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Dependency upgrades
      regexp: '.*?chore\(deps\):.*$'
      order: 2
    - title: Other changes
      order: 999
