basePath: /api/v1
info:
  contact: {}
paths:
  /player/:
    delete:
      consumes:
      - application/json
      description: Delete player by name from database
      parameters:
      - description: player name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: delete player from database
      tags:
      - example
    get:
      consumes:
      - application/json
      description: Get player by name from database
      parameters:
      - description: player name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get player from database
      tags:
      - example
swagger: "2.0"
