// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: .proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbsenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pseudo string  `protobuf:"bytes,1,opt,name=pseudo,proto3" json:"pseudo,omitempty"`
	Date   []int64 `protobuf:"varint,2,rep,packed,name=date,proto3" json:"date,omitempty"`
}

func (x *AbsenceRequest) Reset() {
	*x = AbsenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file___proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbsenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsenceRequest) ProtoMessage() {}

func (x *AbsenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsenceRequest.ProtoReflect.Descriptor instead.
func (*AbsenceRequest) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{0}
}

func (x *AbsenceRequest) GetPseudo() string {
	if x != nil {
		return x.Pseudo
	}
	return ""
}

func (x *AbsenceRequest) GetDate() []int64 {
	if x != nil {
		return x.Date
	}
	return nil
}

type RemoveAbsenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveAbsenceResponse) Reset() {
	*x = RemoveAbsenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file___proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAbsenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAbsenceResponse) ProtoMessage() {}

func (x *RemoveAbsenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAbsenceResponse.ProtoReflect.Descriptor instead.
func (*RemoveAbsenceResponse) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{1}
}

func (x *RemoveAbsenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveAbsenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddAbsenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddAbsenceResponse) Reset() {
	*x = AddAbsenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file___proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAbsenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAbsenceResponse) ProtoMessage() {}

func (x *AddAbsenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAbsenceResponse.ProtoReflect.Descriptor instead.
func (*AddAbsenceResponse) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{2}
}

func (x *AddAbsenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddAbsenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAbsOnRaidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date int64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *ListAbsOnRaidRequest) Reset() {
	*x = ListAbsOnRaidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file___proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAbsOnRaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbsOnRaidRequest) ProtoMessage() {}

func (x *ListAbsOnRaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbsOnRaidRequest.ProtoReflect.Descriptor instead.
func (*ListAbsOnRaidRequest) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{3}
}

func (x *ListAbsOnRaidRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type ListAbsOnRaidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Absences []string `protobuf:"bytes,3,rep,name=absences,proto3" json:"absences,omitempty"`
}

func (x *ListAbsOnRaidResponse) Reset() {
	*x = ListAbsOnRaidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file___proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAbsOnRaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbsOnRaidResponse) ProtoMessage() {}

func (x *ListAbsOnRaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbsOnRaidResponse.ProtoReflect.Descriptor instead.
func (*ListAbsOnRaidResponse) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{4}
}

func (x *ListAbsOnRaidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAbsOnRaidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAbsOnRaidResponse) GetAbsences() []string {
	if x != nil {
		return x.Absences
	}
	return nil
}

var File___proto protoreflect.FileDescriptor

var file___proto_rawDesc = []byte{
	0x0a, 0x06, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x3c, 0x0a,
	0x0e, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x4b, 0x0a, 0x15, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x48, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x41,
	0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x73, 0x4f, 0x6e, 0x52,
	0x61, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x67,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x73, 0x4f, 0x6e, 0x52, 0x61, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x32, 0x80, 0x01, 0x0a, 0x0e, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x62, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x62, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x55, 0x0a, 0x0b, 0x52, 0x61,
	0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x62, 0x73, 0x4f, 0x6e, 0x52, 0x61, 0x69, 0x64, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x73, 0x4f, 0x6e, 0x52, 0x61, 0x69, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x62, 0x73, 0x4f, 0x6e, 0x52, 0x61, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file___proto_rawDescOnce sync.Once
	file___proto_rawDescData = file___proto_rawDesc
)

func file___proto_rawDescGZIP() []byte {
	file___proto_rawDescOnce.Do(func() {
		file___proto_rawDescData = protoimpl.X.CompressGZIP(file___proto_rawDescData)
	})
	return file___proto_rawDescData
}

var file___proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file___proto_goTypes = []interface{}{
	(*AbsenceRequest)(nil),        // 0: rpc.AbsenceRequest
	(*RemoveAbsenceResponse)(nil), // 1: rpc.RemoveAbsenceResponse
	(*AddAbsenceResponse)(nil),    // 2: rpc.AddAbsenceResponse
	(*ListAbsOnRaidRequest)(nil),  // 3: rpc.ListAbsOnRaidRequest
	(*ListAbsOnRaidResponse)(nil), // 4: rpc.ListAbsOnRaidResponse
}
var file___proto_depIdxs = []int32{
	0, // 0: rpc.AbsenceService.Remove:input_type -> rpc.AbsenceRequest
	0, // 1: rpc.AbsenceService.Add:input_type -> rpc.AbsenceRequest
	3, // 2: rpc.RaidService.ListAbsOnRaid:input_type -> rpc.ListAbsOnRaidRequest
	1, // 3: rpc.AbsenceService.Remove:output_type -> rpc.RemoveAbsenceResponse
	2, // 4: rpc.AbsenceService.Add:output_type -> rpc.AddAbsenceResponse
	4, // 5: rpc.RaidService.ListAbsOnRaid:output_type -> rpc.ListAbsOnRaidResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file___proto_init() }
func file___proto_init() {
	if File___proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file___proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbsenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAbsenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAbsenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAbsOnRaidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAbsOnRaidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file___proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file___proto_goTypes,
		DependencyIndexes: file___proto_depIdxs,
		MessageInfos:      file___proto_msgTypes,
	}.Build()
	File___proto = out.File
	file___proto_rawDesc = nil
	file___proto_goTypes = nil
	file___proto_depIdxs = nil
}
