#!/bin/bash

sudo groupadd guildops
sudo useradd -g guildops guildops
sudo chown guildops /usr/bin/guildops
sudo chown guildops /etc/guildops

cat <<EOL > /etc/systemd/system/guildops.service
[Unit]
Description=GuildOps

[Service]
ExecStart=/usr/bin/guildops
Restart=always
User=guildops
Group=guildops
WorkingDirectory=/etc/guildops

[Install]
WantedBy=multi-user.target
EOL

systemctl daemon-reload

systemctl enable guildops.service

systemctl start guildops.service
