---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - Dockerfile

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.8'
          check-latest: true

      - uses: bridgecrewio/checkov-action@c62a2ceacd60b86e57ec72502c567ce3df3012f0
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
