---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - Dockerfile

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.8'
          check-latest: true

      - uses: bridgecrewio/checkov-action@5e86cd541c4b0313548373ee038e5886de0ba918
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
